### PR TITLE
Public Comment 1.2 Editorial comments

### PR DESCRIPTION
**Pull request by chris-little**
Created from @cnreediii Word document. Most changes accepted (except "due to" - "because" preferred).

### CODE REVIEW

**Comment by chris-little** [comment]
@ronaldtse @cmheazel Conflicts with Ron's Merged PR now resolved.

**Review by cmheazel — COMMENTED** [review]
In 06-abstract_model.adoc:

- Line 122 - ordered is misspelled ("dered")
- Line 230 - Standard is misspelled ("Stadnard")

**Comment by chris-little** [comment]
@cmheazel Well spotted! now corrected.

**Comment by chris-little** [comment]
Agreed to merge PR at Temporal DWG on 2023-10-25

**Review by cmheazel — APPROVED** [review]

**Pull request merged**
