### PR TITLE
Chris little editorial tweaks 1

### PR DESCRIPTION
**Pull request by chris-little**
Filled out various sections and deleted template text. corrected a few spelling typos.

### CODE REVIEW

**Comment by chris-little** [comment]
Document is getting longer. May not be a good thing though!

**Review by cmheazel — APPROVED** [review]

**Review by ronaldtse — COMMENTED** [review]
Approved.

**Review by chris-little — COMMENTED** [review]
good

**Review by chris-little — COMMENTED** [review]
@cmheazel Happy to have you as an editor too, but whatn happended to me? Not on Title PAge of PDF. should the Metanorma script say "Author two" or similar?

**Comment by ronaldtse** [comment]
I'll fix it, it's the attribute name.

**Comment by cmheazel** [comment]
@chris-little Sorry Chris.  I missed that error when I reviewed the Metanorma output.  You are listed first in the Asciidoc file.  We just need to make sure that this carries through to the final docs.

**Comment by cmheazel** [comment]
Related question, under what circumstances do you want to rev the document number?

**Comment by chris-little** [comment]
I think we can leave it at 23-032r1 while we tidy up editorial, like pruning bibliography and terms & definitions,

If we make a significant change to, say, the relationships between the top level concepts, such as Association/Aggregation/Composition, though perhaps some cardinalities and inheritance could be considered editorial too.

How does that sound?

**Comment by cmheazel** [comment]
@chris-little That works for me.  

I anticipate at least one major change.  The "Context" section was intended to be a place to hold content while we figure out what to do with it.  This information shows how we are building off of the existing Standards baseline, not just making stuff up.  It looks like I'll have to figure how to do that sooner rather than latter.

**Pull request merged**
