### PR TITLE
Chris little patch 1

### PR DESCRIPTION
**Pull request by chris-little**
Editorial changes to make thoroughly OGCish.
1. need to merge two Clause 6s
2. Need to prune Bibliography and update cross-references

### CODE REVIEW

**Comment by ronaldtse** [comment]
@chris-little @cmheazel I have cleaned up the document syntax for Metanorma (including the bibs and terms) and the associated workflows.

Let me know if this works!

**Review by cmheazel — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @cmheazel @chris-little !

**Review by chris-little — COMMENTED** [review]
I'm glad a Metanorma expert did this re-formatting!

**Comment by chris-little** [comment]
@ronaldtse @cmheazel I think we still need to create the updated docs in PDF, HTML. They still show only one editor, and the REadme link produces a 404.

**Comment by cmheazel** [comment]
@chris-little See pull request #22.

**Pull request merged**
