### PR TITLE
Public comment working branch

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Review by chris-little — CHANGES_REQUESTED** [review]
@ronaldtse @cmheazel Should there be `marign` and `wieght` key words in the html document instead of `margin` and `weight`? Several occurences of each, and I thought I had edited them out previously.

**Review by chris-little — COMMENTED** [review]
@ronaldtse @cmheazel Once the `wieght` and `marign` issue sorted, happy to approve.

**Comment by chris-little** [comment]
@ronaldtse @ghobona The  `wieght` and `marign` issue looks like a Metanorma bug. What is the best way forward please?

**Comment by ronaldtse** [comment]
Sorry @chris-little , those are not meant to exist. Typically in a Metanorma document there is no need to manually set any margin or width. I thought this PR removed them, but if not I’ll update it. I wasn’t the one who added them.

**Comment by ronaldtse** [comment]
@chris-little I don't see

> @ronaldtse @ghobona The `wieght` and `marign` issue looks like a Metanorma bug. What is the best way forward please?

@chris-little I don't see this issue in the generated HTML content which you can download here from the latest build:
* https://github.com/opengeospatial/Temporal-Abstract-Spec/actions/runs/6904461574
* Also attached: [Temporal-Abstract-Spec.zip](https://github.com/opengeospatial/Temporal-Abstract-Spec/files/13481484/Temporal-Abstract-Spec.zip)

As Metanorma best practice we encourage users not to check-in their generated artifacts into version control (Git) but manage them using an alternative process like GitHub Releases.

**Comment by ronaldtse** [comment]
i.e. I would prefer removing these files from version control since they are generated artifacts:

```
23-049.doc
23-049.html
23-049.pdf
23-049.presentation.xml
```

**Review by chris-little — APPROVED** [review]
Very Sensible!

**Review by chris-little — APPROVED** [review]

**Pull request merged**
