### PR TITLE
Update 00-preface.adoc

### PR DESCRIPTION
**Pull request by chris-little**
Public Comment 1.3 add third submitter

### CODE REVIEW

**Comment by ronaldtse** [comment]
@chris-little I've updated the text to show submitter and also a number of formatting fixes. We need one more reviewer for approval to merge. Thanks!

**Comment by ronaldtse** [comment]
Ping @cmheazel @ghobona @gbuehler for one more approval. Thanks!

**Comment by chris-little** [comment]
@ronaldtse Good to get a professional Metanorma expert sorting our amateur efforts! This will look a lots cleaner.

@cmheazel will need to update his fork with the demise of `relaton`.

**Review by cmheazel — APPROVED** [review]
Looks good.  Now let's see if it builds on my machine.

**Pull request merged**
