### PR TITLE
Add a timeline attribute to calendar

### PR DESCRIPTION
**Pull request by chris-little**
Timeline as an attribute of Calendar.

### CODE REVIEW

**Comment by cmheazel** [comment]
Please merge PR #36 first to avoid merge conflicts.

**Review by cmheazel — APPROVED** [review]
Don't forget to update the text as well.

**Comment by chris-little** [comment]
This is an alternative to #PR38

**Comment by chris-little** [comment]
Deleting PR as PR#38 preferred

**Pull request closed without merging**
